---
 {'Logical_systems': {'AG-1000-1': {'BGP': {'to-AG': {'local-ip': '172.100.255.1',
                                                     'neighbors': {'AG-1000-2': '172.100.255.2'}},
                                           'to-Core-RR': {'local-ip': '172.100.255.1',
                                                          'neighbors': {'Core-RR': '172.100.255.255'}},
                                           'to-PAG-Clients': {'local-ip': '172.100.255.1',
                                                              'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                            'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.100': {'description': 'to_AG-1000-2_Pre-agg',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '100',
                                                                   'int_type': 'aggregation',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.22'},
                                                  'ge-0/0/0.101': {'description': 'to_PAG-1000-1',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '101',
                                                                   'int_type': 'aggregation',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.2.0'},
                                                  'ge-0/0/0.104': {'description': 'to_Core-RR',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '104',
                                                                   'int_type': 'core',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.1.4'},
                                                  'ge-0/0/0.300': {'description': 'to_AG-1000-2_Core',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '300',
                                                                   'int_type': 'core',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.1.0'},
                                                  'lo0.1': {'description': 'RID',
                                                            'ifd': 'lo0',
                                                            'iff': 'inet, iso, mpls',
                                                            'ifl': '1',
                                                            'int_type': 'loopback',
                                                            'ipv4_cidr': '32',
                                                            'ipv4_ifa': '172.100.255.1',
                                                            'iso_ifa': '49.0002.1721.0025.5001.00'}},
                                   'LSP': {'AG-1000-1_to_Core-RR': {'from': '172.100.255.1',
                                                                    'to': '172.100.255.255'},
                                           'AG-1000-1_to_PAG-1000-1': {'from': '172.100.255.1',
                                                                       'to': '172.100.255.11'},
                                           'AG-1000-1_to_PAG-1000-2': {'from': '172.100.255.1',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'AG'},
                     'AG-1000-2': {'BGP': {'to-AG': {'local-ip': '172.100.255.2',
                                                     'neighbors': {'AG-1000-1': '172.100.255.1'}},
                                           'to-Core-RR': {'local-ip': '172.100.255.2',
                                                          'neighbors': {'Core-RR': '172.100.255.255'}},
                                           'to-PAG-Clients': {'local-ip': '172.100.255.2',
                                                              'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                            'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.105': {'description': 'to_Core-RR',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '105',
                                                                   'int_type': 'core',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.1.6'},
                                                  'ge-0/0/1.100': {'description': 'to_AG-1000-1_Pre-agg',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '100',
                                                                   'int_type': 'aggregation',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.23'},
                                                  'ge-0/0/1.103': {'description': 'to_PAG-1000-2',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '103',
                                                                   'int_type': 'aggregation',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.2.5'},
                                                  'ge-0/0/1.300': {'description': 'to_AG-1000-1_Core',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '300',
                                                                   'int_type': 'core',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.1.1'},
                                                  'lo0.2': {'description': 'RID',
                                                            'ifd': 'lo0',
                                                            'iff': 'inet, iso, mpls',
                                                            'ifl': '2',
                                                            'int_type': 'loopback',
                                                            'ipv4_cidr': '32',
                                                            'ipv4_ifa': '172.100.255.2',
                                                            'iso_ifa': '49.0002.1721.0025.5002.00'}},
                                   'LSP': {'AG-1000-2_to_Core-RR': {'from': '172.100.255.2',
                                                                    'to': '172.100.255.255'},
                                           'AG-1000-2_to_PAG-1000-1': {'from': '172.100.255.2',
                                                                       'to': '172.100.255.11'},
                                           'AG-1000-2_to_PAG-1000-2': {'from': '172.100.255.2',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'AG'},
                     'Core-RR': {'BGP': {'to-AG-Clients': {'local-ip': '172.100.255.255',
                                                           'neighbors': {'AG-1000-1': '172.100.255.1',
                                                                         'AG-1000-2': '172.100.255.2'}}},
                                 'INTERFACES': {'ge-0/0/1.104': {'description': 'to_AG-1000-1_Core',
                                                                 'ifd': 'ge-0/0/1',
                                                                 'iff': 'inet, iso, mpls',
                                                                 'ifl': '104',
                                                                 'int_type': 'core',
                                                                 'ipv4_cidr': '31',
                                                                 'ipv4_ifa': '172.100.1.5'},
                                                'ge-0/0/1.105': {'description': 'to_AG-1000-2_Core',
                                                                 'ifd': 'ge-0/0/1',
                                                                 'iff': 'inet, iso, mpls',
                                                                 'ifl': '105',
                                                                 'int_type': 'core',
                                                                 'ipv4_cidr': '31',
                                                                 'ipv4_ifa': '172.100.1.7'},
                                                'ge-0/0/4.255': {'description': 'to_Services',
                                                                 'ifd': 'ge-0/0/4',
                                                                 'iff': 'inet',
                                                                 'ifl': '255',
                                                                 'int_type': 'service',
                                                                 'ipv4_cidr': '24',
                                                                 'ipv4_ifa': '10.10.10.10'},
                                                'lo0.3': {'description': 'RID',
                                                          'ifd': 'lo0',
                                                          'iff': 'inet, iso, mpls',
                                                          'ifl': '3',
                                                          'int_type': 'loopback',
                                                          'ipv4_cidr': '32',
                                                          'ipv4_ifa': '172.100.255.255',
                                                          'iso_ifa': '49.0001.1721.0025.5255.00'}},
                                 'LSP': {'Core-RR_to_AG-1000-1': {'from': '172.100.255.255',
                                                                  'to': '172.100.255.1'},
                                         'Core-RR_to_AG-1000-2': {'from': '172.100.255.255',
                                                                  'to': '172.100.255.2'}},
                                 'host_type': 'Core'},
                     'MA-1001-1': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.111',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.112': {'description': 'to_MA-1001-2',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '112',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.2'},
                                                  'ge-0/0/1.111': {'description': 'to_PAG-1000-1',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '111',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.1'},
                                                  'ge-0/0/2.11': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '11',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.11.1'},
                                                  'lo0.111': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '111',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.111',
                                                              'iso_ifa': '49.1001.1721.0025.5111.00'}},
                                   'LSP': {'MA-1001-1_to_PAG-1000-1': {'from': '172.100.255.111',
                                                                       'to': '172.100.255.11'},
                                           'MA-1001-1_to_PAG-1000-2': {'from': '172.100.255.111',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1001-2': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.112',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.113': {'description': 'to_MA-1001-3',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '113',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.4'},
                                                  'ge-0/0/1.112': {'description': 'to_MA-1001-1',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '112',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.3'},
                                                  'ge-0/0/2.12': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '12',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.12.1'},
                                                  'lo0.112': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '112',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.112',
                                                              'iso_ifa': '49.1001.1721.0025.5112.00'}},
                                   'LSP': {'MA-1001-2_to_PAG-1000-1': {'from': '172.100.255.112',
                                                                       'to': '172.100.255.11'},
                                           'MA-1001-2_to_PAG-1000-2': {'from': '172.100.255.112',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1001-3': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.113',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.114': {'description': 'to_MA-1001-4',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '114',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.6'},
                                                  'ge-0/0/1.113': {'description': 'to_MA-1001-2',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '113',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.5'},
                                                  'ge-0/0/2.13': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '13',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.13.1'},
                                                  'lo0.113': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '113',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.113',
                                                              'iso_ifa': '49.1001.1721.0025.5113.00'}},
                                   'LSP': {'MA-1001-3_to_PAG-1000-1': {'from': '172.100.255.113',
                                                                       'to': '172.100.255.11'},
                                           'MA-1001-3_to_PAG-1000-2': {'from': '172.100.255.113',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1001-4': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.114',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.115': {'description': 'to_PAG-1000-2',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '115',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.8'},
                                                  'ge-0/0/1.114': {'description': 'to_MA-1001-3',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '114',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.7'},
                                                  'ge-0/0/2.14': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '14',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.14.1'},
                                                  'lo0.114': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '114',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.114',
                                                              'iso_ifa': '49.1001.1721.0025.5114.00'}},
                                   'LSP': {'MA-1001-4_to_PAG-1000-1': {'from': '172.100.255.114',
                                                                       'to': '172.100.255.11'},
                                           'MA-1001-4_to_PAG-1000-2': {'from': '172.100.255.114',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1002-1': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.121',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.212': {'description': 'to_MA-1002-2',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '212',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.12'},
                                                  'ge-0/0/1.211': {'description': 'to_PAG-1000-1',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '211',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.11'},
                                                  'ge-0/0/2.21': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '21',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.21.1'},
                                                  'lo0.121': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '121',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.121',
                                                              'iso_ifa': '49.1002.1721.0025.5121.00'}},
                                   'LSP': {'MA-1002-1_to_PAG-1000-1': {'from': '172.100.255.121',
                                                                       'to': '172.100.255.11'},
                                           'MA-1002-1_to_PAG-1000-2': {'from': '172.100.255.121',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1002-2': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.122',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.213': {'description': 'to_MA-1002-3',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '213',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.14'},
                                                  'ge-0/0/1.212': {'description': 'to_MA-1002-1',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '212',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.13'},
                                                  'ge-0/0/2.22': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '22',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.22.1'},
                                                  'lo0.122': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '122',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.122',
                                                              'iso_ifa': '49.1002.1721.0025.5122.00'}},
                                   'LSP': {'MA-1002-2_to_PAG-1000-1': {'from': '172.100.255.122',
                                                                       'to': '172.100.255.11'},
                                           'MA-1002-2_to_PAG-1000-2': {'from': '172.100.255.122',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1002-3': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.123',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.214': {'description': 'to_MA-1002-4',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '214',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.16'},
                                                  'ge-0/0/1.213': {'description': 'to_MA-1002-2',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '213',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.15'},
                                                  'ge-0/0/2.23': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '23',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.23.1'},
                                                  'lo0.123': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '123',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.123',
                                                              'iso_ifa': '49.1002.1721.0025.5123.00'}},
                                   'LSP': {'MA-1002-3_to_PAG-1000-1': {'from': '172.100.255.123',
                                                                       'to': '172.100.255.11'},
                                           'MA-1002-3_to_PAG-1000-2': {'from': '172.100.255.123',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1002-4': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.124',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.215': {'description': 'to_MA-1002-5',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '215',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.18'},
                                                  'ge-0/0/1.214': {'description': 'to_MA-1002-3',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '214',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.17'},
                                                  'ge-0/0/2.24': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '24',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.24.1'},
                                                  'lo0.124': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '124',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.124',
                                                              'iso_ifa': '49.1002.1721.0025.5124.00'}},
                                   'LSP': {'MA-1002-4_to_PAG-1000-1': {'from': '172.100.255.124',
                                                                       'to': '172.100.255.11'},
                                           'MA-1002-4_to_PAG-1000-2': {'from': '172.100.255.124',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'MA-1002-5': {'BGP': {'to-PAG-RR': {'local-ip': '172.100.255.125',
                                                         'neighbors': {'PAG-1000-1': '172.100.255.11',
                                                                       'PAG-1000-2': '172.100.255.12'}}},
                                   'INTERFACES': {'ge-0/0/0.216': {'description': 'to_PAG-1000-2',
                                                                   'ifd': 'ge-0/0/0',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '216',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.20'},
                                                  'ge-0/0/1.215': {'description': 'to_MA-1002-4',
                                                                   'ifd': 'ge-0/0/1',
                                                                   'iff': 'inet, iso, mpls',
                                                                   'ifl': '215',
                                                                   'int_type': 'access',
                                                                   'ipv4_cidr': '31',
                                                                   'ipv4_ifa': '172.100.3.19'},
                                                  'ge-0/0/2.25': {'description': 'to_Customers',
                                                                  'ifd': 'ge-0/0/2',
                                                                  'iff': 'inet',
                                                                  'ifl': '25',
                                                                  'int_type': 'customer',
                                                                  'ipv4_cidr': '24',
                                                                  'ipv4_ifa': '192.170.25.1'},
                                                  'lo0.125': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '125',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.125',
                                                              'iso_ifa': '49.1002.1721.0025.5125.00'}},
                                   'LSP': {'MA-1002-5_to_PAG-1000-1': {'from': '172.100.255.125',
                                                                       'to': '172.100.255.11'},
                                           'MA-1002-5_to_PAG-1000-2': {'from': '172.100.255.125',
                                                                       'to': '172.100.255.12'}},
                                   'host_type': 'MA'},
                     'PAG-1000-1': {'BGP': {'to-AG-RR': {'local-ip': '172.100.255.11',
                                                         'neighbors': {'AG-1000-1': '172.100.255.1',
                                                                       'AG-1000-2': '172.100.255.2'}},
                                            'to-MA-Clients': {'local-ip': '172.100.255.11',
                                                              'neighbors': {'MA-1001-1': '172.100.255.111',
                                                                            'MA-1001-2': '172.100.255.112',
                                                                            'MA-1001-3': '172.100.255.113',
                                                                            'MA-1001-4': '172.100.255.114',
                                                                            'MA-1002-1': '172.100.255.121',
                                                                            'MA-1002-2': '172.100.255.122',
                                                                            'MA-1002-3': '172.100.255.123',
                                                                            'MA-1002-4': '172.100.255.124',
                                                                            'MA-1002-5': '172.100.255.125'}},
                                            'to-PAG': {'local-ip': '172.100.255.11',
                                                       'neighbors': {'PAG-1000-2': '172.100.255.12'}}},
                                    'INTERFACES': {'ge-0/0/0.102': {'description': 'to_PAG-1000-2_Pre-agg',
                                                                    'ifd': 'ge-0/0/0',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '102',
                                                                    'int_type': 'aggregation',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.2.2'},
                                                   'ge-0/0/0.110': {'description': 'to_PAG-1000-2_Access',
                                                                    'ifd': 'ge-0/0/0',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '110',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.22'},
                                                   'ge-0/0/0.111': {'description': 'to_MA-1001-1',
                                                                    'ifd': 'ge-0/0/0',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '111',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.0'},
                                                   'ge-0/0/0.211': {'description': 'to_MA-1002-1',
                                                                    'ifd': 'ge-0/0/0',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '211',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.10'},
                                                   'ge-0/0/1.101': {'description': 'to_AG-1000-1',
                                                                    'ifd': 'ge-0/0/1',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '101',
                                                                    'int_type': 'aggregation',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.2.1'},
                                                   'lo0.11': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '11',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.11',
                                                              'iso_ifa': '49.0002.1721.0025.5011.00'}},
                                    'LSP': {'PAG-1000-1_to_AG-1000-1': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.1'},
                                            'PAG-1000-1_to_AG-1000-2': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.2'},
                                            'PAG-1000-1_to_MA-1001-1': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.111'},
                                            'PAG-1000-1_to_MA-1001-2': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.112'},
                                            'PAG-1000-1_to_MA-1001-3': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.113'},
                                            'PAG-1000-1_to_MA-1001-4': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.114'},
                                            'PAG-1000-1_to_MA-1002-1': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.121'},
                                            'PAG-1000-1_to_MA-1002-2': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.122'},
                                            'PAG-1000-1_to_MA-1002-3': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.123'},
                                            'PAG-1000-1_to_MA-1002-4': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.124'},
                                            'PAG-1000-1_to_MA-1002-5': {'from': '172.100.255.11',
                                                                        'to': '172.100.255.125'}},
                                    'host_type': 'PAG'},
                     'PAG-1000-2': {'BGP': {'to-AG-RR': {'local-ip': '172.100.255.12',
                                                         'neighbors': {'AG-1000-1': '172.100.255.1',
                                                                       'AG-1000-2': '172.100.255.2'}},
                                            'to-MA-Clients': {'local-ip': '172.100.255.12',
                                                              'neighbors': {'MA-1001-1': '172.100.255.111',
                                                                            'MA-1001-2': '172.100.255.112',
                                                                            'MA-1001-3': '172.100.255.113',
                                                                            'MA-1001-4': '172.100.255.114',
                                                                            'MA-1002-1': '172.100.255.121',
                                                                            'MA-1002-2': '172.100.255.122',
                                                                            'MA-1002-3': '172.100.255.123',
                                                                            'MA-1002-4': '172.100.255.124',
                                                                            'MA-1002-5': '172.100.255.125'}},
                                            'to-PAG': {'local-ip': '172.100.255.12',
                                                       'neighbors': {'PAG-1000-1': '172.100.255.11'}}},
                                    'INTERFACES': {'ge-0/0/0.103': {'description': 'to_AG-1000-2',
                                                                    'ifd': 'ge-0/0/0',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '103',
                                                                    'int_type': 'aggregation',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.2.4'},
                                                   'ge-0/0/1.102': {'description': 'to_PAG-1000-1_Pre-agg',
                                                                    'ifd': 'ge-0/0/1',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '102',
                                                                    'int_type': 'aggregation',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.2.3'},
                                                   'ge-0/0/1.110': {'description': 'to_PAG-1000-1_Access',
                                                                    'ifd': 'ge-0/0/1',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '110',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.23'},
                                                   'ge-0/0/1.115': {'description': 'to_MA-1001-4',
                                                                    'ifd': 'ge-0/0/1',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '115',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.9'},
                                                   'ge-0/0/1.216': {'description': 'to_MA-1002-5',
                                                                    'ifd': 'ge-0/0/1',
                                                                    'iff': 'inet, iso, mpls',
                                                                    'ifl': '216',
                                                                    'int_type': 'access',
                                                                    'ipv4_cidr': '31',
                                                                    'ipv4_ifa': '172.100.3.21'},
                                                   'lo0.12': {'description': 'RID',
                                                              'ifd': 'lo0',
                                                              'iff': 'inet, iso, mpls',
                                                              'ifl': '12',
                                                              'int_type': 'loopback',
                                                              'ipv4_cidr': '32',
                                                              'ipv4_ifa': '172.100.255.12',
                                                              'iso_ifa': '49.0002.1721.0025.5012.00'}},
                                    'LSP': {'PAG-1000-2_to_AG-1000-1': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.1'},
                                            'PAG-1000-2_to_AG-1000-2': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.2'},
                                            'PAG-1000-2_to_MA-1001-1': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.111'},
                                            'PAG-1000-2_to_MA-1001-2': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.112'},
                                            'PAG-1000-2_to_MA-1001-3': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.113'},
                                            'PAG-1000-2_to_MA-1001-4': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.114'},
                                            'PAG-1000-2_to_MA-1002-1': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.121'},
                                            'PAG-1000-2_to_MA-1002-2': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.122'},
                                            'PAG-1000-2_to_MA-1002-3': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.123'},
                                            'PAG-1000-2_to_MA-1002-4': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.124'},
                                            'PAG-1000-2_to_MA-1002-5': {'from': '172.100.255.12',
                                                                        'to': '172.100.255.125'}},
                                    'host_type': 'PAG'}}}