# for one device, can be given like this:
hosts:
  - device: 10.209.16.204
    username: demo 
    passwd: demo123
tests:
  - test_xml.yml 


###################################
can send mail by specifying:
mail: send_mail.yml

####################################
